# Generated by Django 5.2.8 on 2026-08-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='profile_url',
            field=models.TextField(default='https://dqkuddmtpxwqyjbkamcb.supabase.co/storage/v1/object/public/marketplace/profile_pictures/photo_2026-08-09_18-29-11.jpg', null=True),
        ),
    ]
