# Generated by Django 5.2.8 on 2026-06-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_customusermodel_last_seen_customusermodel_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
