# Generated by Django 5.2.8 on 2026-08-09 16:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_sales_quantity', models.PositiveIntegerField(default=0)),
                ('active_products_count', models.PositiveIntegerField(default=0)),
                ('total_stock_units', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Daily Analytics',
                'verbose_name_plural': 'Daily Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProductStockSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='Products_app.product')),
            ],
            options={
                'verbose_name': 'Product Stock Snapshot',
                'verbose_name_plural': 'Product Stock Snapshots',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['product', '-recorded_at'], name='analytics_p_product_707b82_idx')],
            },
        ),
        migrations.CreateModel(
            name='TopSellingProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('units_sold', models.PositiveIntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('rank', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_selling_records', to='Products_app.product')),
            ],
            options={
                'verbose_name': 'Top Selling Product',
                'verbose_name_plural': 'Top Selling Products',
                'ordering': ['period_start', 'rank'],
                'unique_together': {('product', 'period_start', 'period_end')},
            },
        ),
    ]
