# Generated by Django 5.2.8 on 2026-05-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order', 'Order Update'), ('message', 'New Message'), ('payment', 'Payment Confirmation'), ('general', 'General Notification'), ('like', 'Like'), ('review', 'Review'), ('comment', 'Comment')], max_length=20),
        ),
    ]
