# Generated by Django 5.2.8 on 2026-08-09 16:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products_app', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=255)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Search Queries',
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('view_duration', models.PositiveIntegerField(default=0, help_text='Duration in seconds')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_views', to='customers.vendorcontents')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', '-viewed_at'], name='usersearch__user_id_c28d4c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('view_duration', models.PositiveIntegerField(default=0, help_text='Duration in seconds')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_views', to='Products_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', '-viewed_at'], name='usersearch__user_id_e257dc_idx')],
            },
        ),
    ]
