# Generated by Django 5.2.8 on 2026-08-10 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersearch', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentView',
        ),
    ]
