# Generated by Django 5.2.8 on 2026-08-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='file',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
