# Generated by Django 5.2.8 on 2026-05-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_alter_messagemodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
