# Generated by Django 5.2.8 on 2026-05-30 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_messagemodel_file_alter_messagemodel_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chatapp.messagemodel'),
        ),
    ]
