# Generated by Django 5.2.8 on 2026-08-10 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('usersearch', '0002_delete_contentview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentreview',
            name='content',
        ),
        migrations.RemoveField(
            model_name='contentreview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vendorcontents',
            name='user',
        ),
        migrations.DeleteModel(
            name='ContentLike',
        ),
        migrations.DeleteModel(
            name='ContentReview',
        ),
        migrations.DeleteModel(
            name='VendorContents',
        ),
    ]
