# Generated by Django 5.2.8 on 2026-05-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_contentreview_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorcontents',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
