# Generated by Django 5.2.8 on 2026-06-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kauch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='media_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
