# Generated by Django 5.2.8 on 2026-06-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kauch', '0002_postmodel_media_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='media_type',
            field=models.CharField(choices=[('image', 'image'), ('video', 'video'), ('audio', 'audio')], default='image', max_length=10),
        ),
    ]
