# Generated by Django 5.2.8 on 2026-06-13 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kauch', '0003_alter_postmodel_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='kauch.postcomment'),
        ),
    ]
