# Generated by Django 5.2.8 on 2026-06-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kauch', '0005_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='shares_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
