# Generated by Django 5.2.8 on 2026-08-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_product_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_read_by_buyer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_read_by_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
